[package]
name = "f3repl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dependencies.forth3]
path = "../"
features = ["use-std", "floats", "bitops"]
