[package]
name = "forth3"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hash32 = "0.3.1"

[features]
default = []
use-std = []
floats = []
bitops = []
async = []

[dev-dependencies]
futures = "0.3.28"

[workspace]
# TODO: Move these all to a `crates/` folder once there
# aren't as many in-flight PRs
members = [
    ".",
    "f3repl",
    "forthboy",
]
